Fix SQL Queries
nuclearsilo583/zephyrus-store-preview-new-syntax pull request #160
Opened 2023-04-18 04:15 UTC by strteamservidores

on map load, the plugin was giving a sql error, like this:

```
[store.smx] SQL error happened.
Query: delete `store_items`, `store_equipment`from `store_items`, `store_equipment` where (store_items.unique_id = store_equipment.unique_id) and store_items.date_of_expiration<>0 and store_items.date_of_expiration<1676067429
Error: near "store_items": syntax error
```

i changed the code and made a quick test, seems to work good!

2023-04-18 04:38 UTC, azalty requested changes
This patch doesn't work on SQLite and reverts the changes I've done in #147

2023-04-18 04:40 UTC, strteamservidores commented
> This patch doesn't work on SQLite and reverts the changes I've done in #147

SQLite I didn't get to test it, but the old fix didn't fix it in MySQL, it continued with the error.

2023-04-18 04:42 UTC, azalty commented
I believe this bug was actually fixed on the latest version of the map, and you reintroduced it with this PR.

What indicates this is the fact that the error message prints your changed query (instead of mine).

Furthermore, I don't believe the syntax `DELETE X,X FROM X,X` exists, in either SQLite or MySQL. It doesn't seem to be in either of the documentations.

2023-04-18 04:45 UTC, strteamservidores commented
this https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/pull/147 pull request did not fix the error, I installed the plugin today and the error continues, it only fixed after the changes I made, this in MySQL, I did not test it in SQLite.

2023-04-18 04:51 UTC, strteamservidores commented
i was getting this error: 

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (store_items.unique_id = store_equipment.unique_id) AND store_items.date_o' at line 1`

With this querie:

`DELETE FROM store_items, store_equipment WHERE (store_items.unique_id = store_equipment.unique_id) AND store_items.date_of_expiration != 0 AND store_items.date_of_expiration < 1681787415`

Using this version of plugin: 
https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store/db.sp#L42

2023-04-18 05:21 UTC, azalty commented
Thanks for your reply.

Can you try the current one without the parenthesis of the first WHERE clause?

2023-04-19 21:37 UTC, azalty commented
I created a new PR #161 that adds driver-dependent queries to fix this problem.

Could you please take a look at it to check if it works? I've implemented the exact same query that you for MySQL, so it should work; but hey, we never know when that's @azalty that's coding!

Thanks a lot for reporting and my sincere apologies for breaking the entire plugin for MySQL users for like **2 ENTIRE MONTHS**. You behaved great, was fast to answer and gave me lots of useful infos, thanks ❤️!

2023-04-23 12:57 UTC, nuclearsilo583 commented
#161

2023-04-23 12:57 UTC, closed without merging