Edited entity kill, 'Credits' modified to 'credits', renamed 2 files, fixed toplists, edited database structure and added remove store_logs automatically
nuclearsilo583/zephyrus-store-preview-new-syntax pull request #40
Opened 2021-10-21 16:50 UTC by originalaidn

The RemoveEntity is better than the AcceptEntityInput.

Renamed store_custom_model to store_item_weaponmodel and store_item_hats_thirdpersion to store_item_hats_thirdperson.

Fixed toplists menu bug and added translations and one important 'thing' ==> if the toplists not work.
Also added this fix to the TF2 toplists.

store_logs remove automatically if the sm_store_log_last is not 0.
But:
If you want to use this core (store.sp):
In MySQL:
DELETE store_logs

In SQLite:
if you don't want to delete all data, don't add this version
or
delete the .sq3 file

2021-11-11 11:01 UTC, nuclearsilo583 requested changes
RemoveEntity deletes entity right away, and it can lead to crashes if you or the game uses raw pointers to such entity. AcceptEntityInput removes the entity on the next frame, it's a safe removal.

2021-11-11 12:02 UTC, nuclearsilo583 approved these changes

2021-11-11 12:02 UTC, merged

2022-05-23 22:48 UTC, azalty commented
> RemoveEntity deletes entity right away, and it can lead to crashes if you or the game uses raw pointers to such entity. AcceptEntityInput removes the entity on the next frame, it's a safe removal.

@nuclearsilo583 Apparently it doesn't 🤔 https://cs.alliedmods.net/sourcemod/source/core/smn_entities.cpp#318

RemoveEntity is the same as AcceptEntityInput("Kill") but with additional checks (source: green guy "sappho" on discord & "MAGNAT2645"

You seem to have participated in this discussion as well https://discord.com/channels/335290997317697536/335290997317697536/908308801776656424 - sadly you didn't see the corrections they made right after :
- https://discord.com/channels/335290997317697536/335290997317697536/908311800167157802
- Link to my message https://discord.com/channels/335290997317697536/335290997317697536/959957090904981566

2022-05-23 22:57 UTC, originalaidn commented
Yes, he already knows that, but RemoveEntity has not been included to this day