Fix multiple database connections - issue #86
nuclearsilo583/zephyrus-store-preview-new-syntax pull request #88
Opened 2022-07-28 23:15 UTC by Bernardino18

Credits go to @azalty.
Tested on csgo game servers during 24 hours.

https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/issues/86#issuecomment-1197568588

2022-07-29 01:45 UTC, azalty commented on addons/sourcemod/scripting/store_item_cpsupport.sp
> +	if(g_hDatabase != INVALID_HANDLE)
You can just do `if (g_hDatabase)` :)

2022-07-29 01:48 UTC, azalty requested changes
You should still let the ChatPrefix `strcopy` and `ReadCoreCFG()` functions be ran, so the tag updates properly if the store config changes

2022-07-30 15:25 UTC, merged

2022-07-30 15:25 UTC, nuclearsilo583 commented
thanks for fixing. I currently don't have much free time now.

2022-07-30 17:02 UTC, azalty commented
@nuclearsilo583 I still believe that it's best to still update the store prefix and reload the configs on each map change